# permissions for end users to view prjsecretapis.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: prjsecretapi-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: sample
    app.kubernetes.io/part-of: sample
    app.kubernetes.io/managed-by: kustomize
  name: prjsecretapi-viewer-role
rules:
- apiGroups:
  - prj-secret.kalrainfosystems.com
  resources:
  - prjsecretapis
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - prj-secret.kalrainfosystems.com
  resources:
  - prjsecretapis/status
  verbs:
  - get
