---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - prj-secret.kalrainfosystems.com
  resources:
  - prjsecretapis
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - prj-secret.kalrainfosystems.com
  resources:
  - prjsecretapis/finalizers
  verbs:
  - update
- apiGroups:
  - prj-secret.kalrainfosystems.com
  resources:
  - prjsecretapis/status
  verbs:
  - get
  - patch
  - update
